#############################################################################
# Makefile for building: release/microscope_app
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  microscope_app.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile microscope_app.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DMINDVISION_QOBJECT_LIBRARY -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -I/home/davidek/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/include/python3.11 -I/home/davidek/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/include/python3.11 -O2 -std=gnu++2a -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt6/Qsci -Isrc/microscope_app -Isrc/mindvision_qobject/Include -Isrc/mindvision_qobject/src -Isrc/cnc_control_panel_qobject/src -Isrc/serial_qobject/src -Isrc/led_controller_qobject/src -Isrc/color_picker_widget_qobject/src -Isrc/intensity_chart_qobject/src -Isrc/mosaic_panel_qobject/src -Isrc/editor_qobject/src -Isrc/scan_config_paneL_qobject/src -Isrc/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -Irelease/.moc -Irelease/.ui -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = microscope_app1.0.0
DISTDIR = /home/davidek/src/microtools/microscope_app/release/.obj/microscope_app1.0.0
LINK          = g++
LFLAGS        = -Wl,--disable-new-dtags -Wl,-rpath,/home/davidek/src/microtools/microscope_app/.venv/lib/python3.11/site-packages/PySide6/Qt/lib -Wl,-rpath,/usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/local/cuda/targets/x86_64-linux/lib -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) -L/usr/lib/x86_64-linux-gnu -lqscintilla2_qt6 -L/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Lib -lMVSDK -L/home/davidek/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib -lpython3.11 -ldl -lutil -lm -lnvinfer -lnvinfer_plugin -L/usr/local/cuda/targets/x86_64-linux/lib -lcudart /usr/lib/x86_64-linux-gnu/libQt6Widgets.so /usr/lib/x86_64-linux-gnu/libQt6Gui.so /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/x86_64-linux-gnu/libQt6SerialPort.so /usr/lib/x86_64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = release/.obj/

####### Files

SOURCES       = src/microscope_app/main.cpp \
		src/microscope_app/MainWindow.cpp \
		src/microscope_app/microscope_app_python.cpp \
		src/cnc_control_panel_qobject/src/CNCControlPanel.cpp \
		src/mosaic_panel_qobject/src/MosaicWidget.cpp \
		src/mosaic_panel_qobject/src/MosaicPanel.cpp \
		src/intensity_chart_qobject/src/IntensityChart.cpp \
		src/color_picker_widget_qobject/src/ColorPickerWidget.cpp \
		src/led_controller_qobject/src/LEDController.cpp \
		src/scan_config_paneL_qobject/src/ScanConfigPanel.cpp \
		src/yolo_inference_qobject/src/YOLOInferenceWorker.cpp \
		src/editor_qobject/src/PythonScintillaEditor.cpp \
		src/mindvision_qobject/src/MindVisionCamera.cpp \
		src/mindvision_qobject/src/VideoThread.cpp \
		src/serial_qobject/src/SerialWorker.cpp release/.moc/moc_MainWindow.cpp \
		release/.moc/moc_CNCControlPanel.cpp \
		release/.moc/moc_MosaicWidget.cpp \
		release/.moc/moc_MosaicPanel.cpp \
		release/.moc/moc_IntensityChart.cpp \
		release/.moc/moc_ColorPickerWidget.cpp \
		release/.moc/moc_LEDController.cpp \
		release/.moc/moc_ScanConfigPanel.cpp \
		release/.moc/moc_YOLOInferenceWorker.cpp \
		release/.moc/moc_PythonScintillaEditor.cpp \
		release/.moc/moc_MindVisionCamera.cpp \
		release/.moc/moc_VideoThread.cpp \
		release/.moc/moc_SerialWorker.cpp
OBJECTS       = release/.obj/main.o \
		release/.obj/MainWindow.o \
		release/.obj/microscope_app_python.o \
		release/.obj/CNCControlPanel.o \
		release/.obj/MosaicWidget.o \
		release/.obj/MosaicPanel.o \
		release/.obj/IntensityChart.o \
		release/.obj/ColorPickerWidget.o \
		release/.obj/LEDController.o \
		release/.obj/ScanConfigPanel.o \
		release/.obj/YOLOInferenceWorker.o \
		release/.obj/PythonScintillaEditor.o \
		release/.obj/MindVisionCamera.o \
		release/.obj/VideoThread.o \
		release/.obj/SerialWorker.o \
		release/.obj/moc_MainWindow.o \
		release/.obj/moc_CNCControlPanel.o \
		release/.obj/moc_MosaicWidget.o \
		release/.obj/moc_MosaicPanel.o \
		release/.obj/moc_IntensityChart.o \
		release/.obj/moc_ColorPickerWidget.o \
		release/.obj/moc_LEDController.o \
		release/.obj/moc_ScanConfigPanel.o \
		release/.obj/moc_YOLOInferenceWorker.o \
		release/.obj/moc_PythonScintillaEditor.o \
		release/.obj/moc_MindVisionCamera.o \
		release/.obj/moc_VideoThread.o \
		release/.obj/moc_SerialWorker.o
DIST          = /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_KUserFeedbackCoreQt6.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_KUserFeedbackWidgetsQt6.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_languageserver_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_repparser.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		microscope_app.pro src/microscope_app/MainWindow.h \
		src/cnc_control_panel_qobject/src/CNCControlPanel.h \
		src/mosaic_panel_qobject/src/MosaicWidget.h \
		src/mosaic_panel_qobject/src/MosaicPanel.h \
		src/intensity_chart_qobject/src/IntensityChart.h \
		src/color_picker_widget_qobject/src/ColorPickerWidget.h \
		src/led_controller_qobject/src/LEDController.h \
		src/scan_config_paneL_qobject/src/ScanConfigPanel.h \
		src/yolo_inference_qobject/src/YOLOInferenceWorker.h \
		src/editor_qobject/src/PythonScintillaEditor.h \
		src/mindvision_qobject/src/MindVisionCamera.h \
		src/mindvision_qobject/src/VideoThread.h \
		src/mindvision_qobject/src/mindvision_qobject_global.h \
		src/serial_qobject/src/SerialWorker.h src/microscope_app/main.cpp \
		src/microscope_app/MainWindow.cpp \
		src/microscope_app/microscope_app_python.cpp \
		src/cnc_control_panel_qobject/src/CNCControlPanel.cpp \
		src/mosaic_panel_qobject/src/MosaicWidget.cpp \
		src/mosaic_panel_qobject/src/MosaicPanel.cpp \
		src/intensity_chart_qobject/src/IntensityChart.cpp \
		src/color_picker_widget_qobject/src/ColorPickerWidget.cpp \
		src/led_controller_qobject/src/LEDController.cpp \
		src/scan_config_paneL_qobject/src/ScanConfigPanel.cpp \
		src/yolo_inference_qobject/src/YOLOInferenceWorker.cpp \
		src/editor_qobject/src/PythonScintillaEditor.cpp \
		src/mindvision_qobject/src/MindVisionCamera.cpp \
		src/mindvision_qobject/src/VideoThread.cpp \
		src/serial_qobject/src/SerialWorker.cpp
QMAKE_TARGET  = microscope_app
DESTDIR       = release/
TARGET        = release/microscope_app


first: all
####### Build rules

release/microscope_app: release/.ui/ui_MainWindow.h $(OBJECTS)  
	@test -d release/ || mkdir -p release/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)
	rm -f ./release/_microscope_app_cpp.so 
	 g++ -Wl,--disable-new-dtags -Wl,-rpath,/home/davidek/src/microtools/microscope_app/.venv/lib/python3.11/site-packages/PySide6/Qt/lib -Wl,-rpath,/usr/lib/x86_64-linux-gnu -Wl,-rpath,/usr/local/cuda/targets/x86_64-linux/lib -shared -o ./release/_microscope_app_cpp.so ./release/.obj/*.o -L/usr/lib/x86_64-linux-gnu -lqscintilla2_qt6 -L/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Lib -lMVSDK -L/home/davidek/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib -lpython3.11 -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -lnvinfer -lnvinfer_plugin -L/usr/local/cuda/targets/x86_64-linux/lib -lcudart /usr/lib/x86_64-linux-gnu/libQt6Widgets.so /usr/lib/x86_64-linux-gnu/libQt6Gui.so /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/x86_64-linux-gnu/libQt6SerialPort.so /usr/lib/x86_64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL

Makefile: microscope_app.pro /usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_KUserFeedbackCoreQt6.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_KUserFeedbackWidgetsQt6.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_languageserver_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_repparser.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		microscope_app.pro \
		/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt6SerialPort.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile microscope_app.pro
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_KUserFeedbackCoreQt6.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_KUserFeedbackWidgetsQt6.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core5compat.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_datavisualizationqml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_httpserver.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_jsonrpc_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_languageserver_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_networkauth.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_pdfquick.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3d.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dphysics.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_repparser.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_scxml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_scxmlqml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sensorsquick.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_serialbus.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_shadertools.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_statemachine.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_statemachineqml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_tools_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginequick.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webview.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_webviewquick.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf:
microscope_app.pro:
/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt6Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt6SerialPort.prl:
/usr/lib/x86_64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile microscope_app.pro

qmake_all: FORCE


all: Makefile release/microscope_app

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/microscope_app/MainWindow.h src/cnc_control_panel_qobject/src/CNCControlPanel.h src/mosaic_panel_qobject/src/MosaicWidget.h src/mosaic_panel_qobject/src/MosaicPanel.h src/intensity_chart_qobject/src/IntensityChart.h src/color_picker_widget_qobject/src/ColorPickerWidget.h src/led_controller_qobject/src/LEDController.h src/scan_config_paneL_qobject/src/ScanConfigPanel.h src/yolo_inference_qobject/src/YOLOInferenceWorker.h src/editor_qobject/src/PythonScintillaEditor.h src/mindvision_qobject/src/MindVisionCamera.h src/mindvision_qobject/src/VideoThread.h src/mindvision_qobject/src/mindvision_qobject_global.h src/serial_qobject/src/SerialWorker.h $(DISTDIR)/
	$(COPY_FILE) --parents src/microscope_app/main.cpp src/microscope_app/MainWindow.cpp src/microscope_app/microscope_app_python.cpp src/cnc_control_panel_qobject/src/CNCControlPanel.cpp src/mosaic_panel_qobject/src/MosaicWidget.cpp src/mosaic_panel_qobject/src/MosaicPanel.cpp src/intensity_chart_qobject/src/IntensityChart.cpp src/color_picker_widget_qobject/src/ColorPickerWidget.cpp src/led_controller_qobject/src/LEDController.cpp src/scan_config_paneL_qobject/src/ScanConfigPanel.cpp src/yolo_inference_qobject/src/YOLOInferenceWorker.cpp src/editor_qobject/src/PythonScintillaEditor.cpp src/mindvision_qobject/src/MindVisionCamera.cpp src/mindvision_qobject/src/VideoThread.cpp src/serial_qobject/src/SerialWorker.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/microscope_app/MainWindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: release/.moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) release/.moc/moc_predefs.h
release/.moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -I/home/davidek/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/include/python3.11 -I/home/davidek/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/include/python3.11 -O2 -std=gnu++2a -Wall -Wextra -fPIC -dM -E -o release/.moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: release/.moc/moc_MainWindow.cpp release/.moc/moc_CNCControlPanel.cpp release/.moc/moc_MosaicWidget.cpp release/.moc/moc_MosaicPanel.cpp release/.moc/moc_IntensityChart.cpp release/.moc/moc_ColorPickerWidget.cpp release/.moc/moc_LEDController.cpp release/.moc/moc_ScanConfigPanel.cpp release/.moc/moc_YOLOInferenceWorker.cpp release/.moc/moc_PythonScintillaEditor.cpp release/.moc/moc_MindVisionCamera.cpp release/.moc/moc_VideoThread.cpp release/.moc/moc_SerialWorker.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) release/.moc/moc_MainWindow.cpp release/.moc/moc_CNCControlPanel.cpp release/.moc/moc_MosaicWidget.cpp release/.moc/moc_MosaicPanel.cpp release/.moc/moc_IntensityChart.cpp release/.moc/moc_ColorPickerWidget.cpp release/.moc/moc_LEDController.cpp release/.moc/moc_ScanConfigPanel.cpp release/.moc/moc_YOLOInferenceWorker.cpp release/.moc/moc_PythonScintillaEditor.cpp release/.moc/moc_MindVisionCamera.cpp release/.moc/moc_VideoThread.cpp release/.moc/moc_SerialWorker.cpp
release/.moc/moc_MainWindow.cpp: src/microscope_app/MainWindow.h \
		src/yolo_inference_qobject/src/YOLOInferenceWorker.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/microscope_app/MainWindow.h -o release/.moc/moc_MainWindow.cpp

release/.moc/moc_CNCControlPanel.cpp: src/cnc_control_panel_qobject/src/CNCControlPanel.h \
		src/serial_qobject/src/SerialWorker.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/cnc_control_panel_qobject/src/CNCControlPanel.h -o release/.moc/moc_CNCControlPanel.cpp

release/.moc/moc_MosaicWidget.cpp: src/mosaic_panel_qobject/src/MosaicWidget.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mosaic_panel_qobject/src/MosaicWidget.h -o release/.moc/moc_MosaicWidget.cpp

release/.moc/moc_MosaicPanel.cpp: src/mosaic_panel_qobject/src/MosaicPanel.h \
		src/mosaic_panel_qobject/src/MosaicWidget.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mosaic_panel_qobject/src/MosaicPanel.h -o release/.moc/moc_MosaicPanel.cpp

release/.moc/moc_IntensityChart.cpp: src/intensity_chart_qobject/src/IntensityChart.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/intensity_chart_qobject/src/IntensityChart.h -o release/.moc/moc_IntensityChart.cpp

release/.moc/moc_ColorPickerWidget.cpp: src/color_picker_widget_qobject/src/ColorPickerWidget.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/color_picker_widget_qobject/src/ColorPickerWidget.h -o release/.moc/moc_ColorPickerWidget.cpp

release/.moc/moc_LEDController.cpp: src/led_controller_qobject/src/LEDController.h \
		src/serial_qobject/src/SerialWorker.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/led_controller_qobject/src/LEDController.h -o release/.moc/moc_LEDController.cpp

release/.moc/moc_ScanConfigPanel.cpp: src/scan_config_paneL_qobject/src/ScanConfigPanel.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/scan_config_paneL_qobject/src/ScanConfigPanel.h -o release/.moc/moc_ScanConfigPanel.cpp

release/.moc/moc_YOLOInferenceWorker.cpp: src/yolo_inference_qobject/src/YOLOInferenceWorker.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/yolo_inference_qobject/src/YOLOInferenceWorker.h -o release/.moc/moc_YOLOInferenceWorker.cpp

release/.moc/moc_PythonScintillaEditor.cpp: src/editor_qobject/src/PythonScintillaEditor.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/editor_qobject/src/PythonScintillaEditor.h -o release/.moc/moc_PythonScintillaEditor.cpp

release/.moc/moc_MindVisionCamera.cpp: src/mindvision_qobject/src/MindVisionCamera.h \
		src/mindvision_qobject/src/mindvision_qobject_global.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mindvision_qobject/src/MindVisionCamera.h -o release/.moc/moc_MindVisionCamera.cpp

release/.moc/moc_VideoThread.cpp: src/mindvision_qobject/src/VideoThread.h \
		src/mindvision_qobject/src/mindvision_qobject_global.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mindvision_qobject/src/VideoThread.h -o release/.moc/moc_VideoThread.cpp

release/.moc/moc_SerialWorker.cpp: src/serial_qobject/src/SerialWorker.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/serial_qobject/src/SerialWorker.h -o release/.moc/moc_SerialWorker.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all: release/.moc/MindVisionCamera.moc
compiler_moc_source_clean:
	-$(DEL_FILE) release/.moc/MindVisionCamera.moc
release/.moc/MindVisionCamera.moc: src/mindvision_qobject/src/MindVisionCamera.cpp \
		src/mindvision_qobject/src/MindVisionCamera.h \
		src/mindvision_qobject/src/mindvision_qobject_global.h \
		src/mindvision_qobject/src/VideoThread.h \
		src/mindvision_qobject/Include/CameraApi.h \
		src/mindvision_qobject/Include/CameraDefine.h \
		src/mindvision_qobject/Include/CameraStatus.h \
		release/.moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/davidek/src/microtools/microscope_app/release/.moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/davidek/src/microtools/microscope_app -I/usr/include/x86_64-linux-gnu/qt6/Qsci -I/home/davidek/src/microtools/microscope_app/src/microscope_app -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/Include -I/home/davidek/src/microtools/microscope_app/src/mindvision_qobject/src -I/home/davidek/src/microtools/microscope_app/src/cnc_control_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/serial_qobject/src -I/home/davidek/src/microtools/microscope_app/src/led_controller_qobject/src -I/home/davidek/src/microtools/microscope_app/src/color_picker_widget_qobject/src -I/home/davidek/src/microtools/microscope_app/src/intensity_chart_qobject/src -I/home/davidek/src/microtools/microscope_app/src/mosaic_panel_qobject/src -I/home/davidek/src/microtools/microscope_app/src/editor_qobject/src -I/home/davidek/src/microtools/microscope_app/src/scan_config_paneL_qobject/src -I/home/davidek/src/microtools/microscope_app/src/yolo_inference_qobject/src -I/usr/include/x86_64-linux-gnu -I/usr/local/cuda/targets/x86_64-linux/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtSerialPort -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mindvision_qobject/src/MindVisionCamera.cpp -o release/.moc/MindVisionCamera.moc

compiler_uic_make_all: release/.ui/ui_MainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) release/.ui/ui_MainWindow.h
release/.ui/ui_MainWindow.h: src/microscope_app/MainWindow.ui \
		/usr/lib/qt6/libexec/uic \
		src/cnc_control_panel_qobject/src/CNCControlPanel.h \
		src/intensity_chart_qobject/src/IntensityChart.h \
		src/color_picker_widget_qobject/src/ColorPickerWidget.h \
		src/serial_qobject/src/SerialWorker.h
	/usr/lib/qt6/libexec/uic src/microscope_app/MainWindow.ui -o release/.ui/ui_MainWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

release/.obj/main.o: src/microscope_app/main.cpp src/microscope_app/MainWindow.h \
		src/yolo_inference_qobject/src/YOLOInferenceWorker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/main.o src/microscope_app/main.cpp

release/.obj/MainWindow.o: src/microscope_app/MainWindow.cpp src/microscope_app/MainWindow.h \
		src/yolo_inference_qobject/src/YOLOInferenceWorker.h \
		release/.ui/ui_MainWindow.h \
		src/cnc_control_panel_qobject/src/CNCControlPanel.h \
		src/serial_qobject/src/SerialWorker.h \
		src/color_picker_widget_qobject/src/ColorPickerWidget.h \
		src/intensity_chart_qobject/src/IntensityChart.h \
		src/mindvision_qobject/src/MindVisionCamera.h \
		src/mindvision_qobject/src/mindvision_qobject_global.h \
		src/mindvision_qobject/src/VideoThread.h \
		src/led_controller_qobject/src/LEDController.h \
		src/mosaic_panel_qobject/src/MosaicPanel.h \
		src/mosaic_panel_qobject/src/MosaicWidget.h \
		src/scan_config_paneL_qobject/src/ScanConfigPanel.h \
		src/editor_qobject/src/PythonScintillaEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/MainWindow.o src/microscope_app/MainWindow.cpp

release/.obj/microscope_app_python.o: src/microscope_app/microscope_app_python.cpp src/microscope_app/MainWindow.h \
		src/yolo_inference_qobject/src/YOLOInferenceWorker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/microscope_app_python.o src/microscope_app/microscope_app_python.cpp

release/.obj/CNCControlPanel.o: src/cnc_control_panel_qobject/src/CNCControlPanel.cpp src/cnc_control_panel_qobject/src/CNCControlPanel.h \
		src/serial_qobject/src/SerialWorker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/CNCControlPanel.o src/cnc_control_panel_qobject/src/CNCControlPanel.cpp

release/.obj/MosaicWidget.o: src/mosaic_panel_qobject/src/MosaicWidget.cpp src/mosaic_panel_qobject/src/MosaicWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/MosaicWidget.o src/mosaic_panel_qobject/src/MosaicWidget.cpp

release/.obj/MosaicPanel.o: src/mosaic_panel_qobject/src/MosaicPanel.cpp src/mosaic_panel_qobject/src/MosaicPanel.h \
		src/mosaic_panel_qobject/src/MosaicWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/MosaicPanel.o src/mosaic_panel_qobject/src/MosaicPanel.cpp

release/.obj/IntensityChart.o: src/intensity_chart_qobject/src/IntensityChart.cpp src/intensity_chart_qobject/src/IntensityChart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/IntensityChart.o src/intensity_chart_qobject/src/IntensityChart.cpp

release/.obj/ColorPickerWidget.o: src/color_picker_widget_qobject/src/ColorPickerWidget.cpp src/color_picker_widget_qobject/src/ColorPickerWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/ColorPickerWidget.o src/color_picker_widget_qobject/src/ColorPickerWidget.cpp

release/.obj/LEDController.o: src/led_controller_qobject/src/LEDController.cpp src/led_controller_qobject/src/LEDController.h \
		src/serial_qobject/src/SerialWorker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/LEDController.o src/led_controller_qobject/src/LEDController.cpp

release/.obj/ScanConfigPanel.o: src/scan_config_paneL_qobject/src/ScanConfigPanel.cpp src/scan_config_paneL_qobject/src/ScanConfigPanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/ScanConfigPanel.o src/scan_config_paneL_qobject/src/ScanConfigPanel.cpp

release/.obj/YOLOInferenceWorker.o: src/yolo_inference_qobject/src/YOLOInferenceWorker.cpp src/yolo_inference_qobject/src/YOLOInferenceWorker.h \
		/usr/local/cuda/targets/x86_64-linux/include/cuda_runtime_api.h \
		/usr/local/cuda/targets/x86_64-linux/include/crt/host_defines.h \
		/usr/local/cuda/targets/x86_64-linux/include/builtin_types.h \
		/usr/local/cuda/targets/x86_64-linux/include/device_types.h \
		/usr/local/cuda/targets/x86_64-linux/include/driver_types.h \
		/usr/local/cuda/targets/x86_64-linux/include/vector_types.h \
		/usr/local/cuda/targets/x86_64-linux/include/surface_types.h \
		/usr/local/cuda/targets/x86_64-linux/include/texture_types.h \
		/usr/local/cuda/targets/x86_64-linux/include/cuda_device_runtime_api.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/YOLOInferenceWorker.o src/yolo_inference_qobject/src/YOLOInferenceWorker.cpp

release/.obj/PythonScintillaEditor.o: src/editor_qobject/src/PythonScintillaEditor.cpp src/editor_qobject/src/PythonScintillaEditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/PythonScintillaEditor.o src/editor_qobject/src/PythonScintillaEditor.cpp

release/.obj/MindVisionCamera.o: src/mindvision_qobject/src/MindVisionCamera.cpp src/mindvision_qobject/src/MindVisionCamera.h \
		src/mindvision_qobject/src/mindvision_qobject_global.h \
		src/mindvision_qobject/src/VideoThread.h \
		src/mindvision_qobject/Include/CameraApi.h \
		src/mindvision_qobject/Include/CameraDefine.h \
		src/mindvision_qobject/Include/CameraStatus.h \
		release/.moc/MindVisionCamera.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/MindVisionCamera.o src/mindvision_qobject/src/MindVisionCamera.cpp

release/.obj/VideoThread.o: src/mindvision_qobject/src/VideoThread.cpp src/mindvision_qobject/src/VideoThread.h \
		src/mindvision_qobject/src/mindvision_qobject_global.h \
		src/mindvision_qobject/src/MindVisionCamera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/VideoThread.o src/mindvision_qobject/src/VideoThread.cpp

release/.obj/SerialWorker.o: src/serial_qobject/src/SerialWorker.cpp src/serial_qobject/src/SerialWorker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/SerialWorker.o src/serial_qobject/src/SerialWorker.cpp

release/.obj/moc_MainWindow.o: release/.moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_MainWindow.o release/.moc/moc_MainWindow.cpp

release/.obj/moc_CNCControlPanel.o: release/.moc/moc_CNCControlPanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_CNCControlPanel.o release/.moc/moc_CNCControlPanel.cpp

release/.obj/moc_MosaicWidget.o: release/.moc/moc_MosaicWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_MosaicWidget.o release/.moc/moc_MosaicWidget.cpp

release/.obj/moc_MosaicPanel.o: release/.moc/moc_MosaicPanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_MosaicPanel.o release/.moc/moc_MosaicPanel.cpp

release/.obj/moc_IntensityChart.o: release/.moc/moc_IntensityChart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_IntensityChart.o release/.moc/moc_IntensityChart.cpp

release/.obj/moc_ColorPickerWidget.o: release/.moc/moc_ColorPickerWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_ColorPickerWidget.o release/.moc/moc_ColorPickerWidget.cpp

release/.obj/moc_LEDController.o: release/.moc/moc_LEDController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_LEDController.o release/.moc/moc_LEDController.cpp

release/.obj/moc_ScanConfigPanel.o: release/.moc/moc_ScanConfigPanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_ScanConfigPanel.o release/.moc/moc_ScanConfigPanel.cpp

release/.obj/moc_YOLOInferenceWorker.o: release/.moc/moc_YOLOInferenceWorker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_YOLOInferenceWorker.o release/.moc/moc_YOLOInferenceWorker.cpp

release/.obj/moc_PythonScintillaEditor.o: release/.moc/moc_PythonScintillaEditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_PythonScintillaEditor.o release/.moc/moc_PythonScintillaEditor.cpp

release/.obj/moc_MindVisionCamera.o: release/.moc/moc_MindVisionCamera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_MindVisionCamera.o release/.moc/moc_MindVisionCamera.cpp

release/.obj/moc_VideoThread.o: release/.moc/moc_VideoThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_VideoThread.o release/.moc/moc_VideoThread.cpp

release/.obj/moc_SerialWorker.o: release/.moc/moc_SerialWorker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o release/.obj/moc_SerialWorker.o release/.moc/moc_SerialWorker.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

